apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "call-center.fullname" . }}-uploaded
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "call-center.fullname" . }}-userdata
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi